variables:
  IMAGES: "nginx node python alpine"
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_DRIVER: overlay2

image: docker:19.03

services:
  - name: docker:19.03-dind
    alias: docker
    command: ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]

build-and-scan:
  stage: build
  script:
    - docker info
    - echo "192.168.20.200 uber.cwpp.com" >> /etc/hosts
    - |
      wget --no-check-certificate --header "Authorization: Basic $(echo -n $PCC_USER:$PCC_PASS | base64 | tr -d '\n')" "$PCC_CONSOLE_URL/api/v1/util/twistcli"
      chmod a+x ./twistcli

      for IMAGE in $IMAGES; do
        IMAGE_NAME="custom-${IMAGE}:${CI_COMMIT_SHORT_SHA}"
        docker build -t "$IMAGE_NAME" "$CI_PROJECT_DIR/$IMAGE"
        ./twistcli images scan \
          --docker-address unix:///var/run/docker.sock \
          --address "$PCC_CONSOLE_URL" \
          --user "$PCC_USER" \
          --password "$PCC_PASS" \
          --details "$IMAGE_NAME"
      done
